### ISSUE TITLE
Serverless plugin "serverless-newrelic-layers" not found

### ISSUE THREAD

**Issue by krlozadan** [iopipe/serverless-newrelic-lambda-layers#17]
Hi,

I currently have a serverless project with NR's monitoring using the manual instrumentation and I wanted to give this new plugin a try. The project is using serverless webpack and looking at your code, I'm pretty sure there's a naming issue [here](https://github.com/iopipe/serverless-newrelic-lambda-layers/blob/master/src/index.ts#L57) where the name you should be checking is `serverless-newrelic-lambda-layers`, not `serverless-newrelic-layers` as since it can't find it, indexOf returns -1

Here's how my plugins look like:
```yaml
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-newrelic-lambda-layers
```

**Comment by mrickard** [comment]
Hi @krlozadan ! Thank you for the report!  It does look like the naming got out of sync; we'll have an update for that shortly.

**Comment by krlozadan** [comment]
Thank you! I was about to create a PR XD
