### ISSUE TITLE
cloudWatchFilter option throws Type Error

### ISSUE THREAD

**Issue by krlozadan** [iopipe/serverless-newrelic-lambda-layers#19]
Hi, when I try to deploy my functions with the `cloudWatchFilter: '*'` option the following error:

```bash
TypeError: cloudWatchFilter.find is not a function at NewRelicLambdaLayerPlugin.<anonymous> (/Users/usr/project/node_modules/serverless-newrelic-lambda-layers/dist/index.js:69:35)
```

If I remove the option it completes successfully. 

BTW... how can I make sure the lambda instrumentation worked? I cannot see any layers created in my AWS console...🤔

**Comment by mrickard** [comment]
@krlozadan Do you have a layers ARN for your region? https://nr-layers.iopipe.com/

**Comment by krlozadan** [comment]
@mrickard From what I understand in the docs... the ARN should get automatically fetched right?
After deployment I'm getting:
```
layers:
  None

Serverless: Configuring New Relic log subscription for **function name**
......... all my functions

Serverless: Found log subscription for **function name**, verifying configuration
......... all my functions
```

**Comment by krlozadan** [comment]
As a side note, I think the automatic **layerArn** resolver is not working because I wasn't getting anything in the New Relic console until I specified the ARN from the website you provided me.

**Comment by kolanos** [comment]
The output here:

```
layers:
  None
```

Just means your `serverless.yml` didn't publish any of its own layers.

**Comment by krlozadan** [comment]
Thanks for the clarification @kolanos ... you're right. Now, the plugin states:

> layerArn (optional)
Pin to a specific layer version. The latest layer ARN is automatically fetched from the New Relic Layers API

Which doesn't didn't really work, I had to specify the ARN it to make my lambdas send information to New Relic again. This actually should be its own thread. Sorry...  

The main point here is the **Type Error** when specifying the **cloudWatchFilter**, in this case to "*"

**Comment by kolanos** [comment]
@krlozadan Yes, it looks like `cloudWatchFilter` is being parsed by YAML  into something other than an array. The plugin should definitely guard against that and can provide a useful log message.
