### ISSUE TITLE
When plugins is an object, execution fails with "plugins.indexOf is not a function"

### ISSUE THREAD

**Issue by sternberginator** [iopipe/serverless-newrelic-lambda-layers#26]
The `plugins` section can be specified as an array of plugin names OR as an object specifying `localPath` and `modules` (see https://serverless.com/framework/docs/providers/aws/guide/plugins#installing-plugins)

When checking the order of plugins, after this line https://github.com/iopipe/serverless-newrelic-lambda-layers/blob/df0b961515fc1abab8f51260874fdd61fd37e6d5/src/index.ts#L53, it is assumed that `plugins` is an array, so if it's an object the calls to `indexOf` will throw an error.

**Comment by sternberginator** [comment]
I don't know how I can push code to open a PR but my proposed fix is to replace that line with:
```
let plugins = _.get(this.serverless, "service.plugins", []);
if (typeof plugins === 'object') plugins = plugins.modules;
```

**Comment by kamaz** [comment]
Creating a PR is really simple. I've copied the link below that takes you step by step. I hope it help.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
