### ISSUE TITLE
Testing strategy 

### ISSUE THREAD

**Issue by kamaz** [iopipe/serverless-newrelic-lambda-layers#29]
I was wondering if you have decided on some kind of testing strategy (unit/integration) / tooling (jest). 

I would be happy to help if you need any also would like to check-in tests for the functionality that I've added.

**Comment by mrickard** [comment]
@kamaz Thank you for your contributions!  We've used both jest and mocha/chai tooling for tests, and I'm not strongly opinionated on which one.  (It sounds like you'd be happy to contribute jest tests, and I'm totally in favor of that.)

As far as unit and integration tests, I can see roles for each, though concentrating first on unit tests is a good practice.

**Comment by kamaz** [comment]
Great I will create a PR for that as well. 

Thanks for sharing the plugin. It saves us a little bit time 😄

**Comment by mrickard** [comment]
@kamaz I'll be archiving this repo, and pushing over to New Relic.  Commit history should stay the same.  See #30  for updates.

**Comment by kamaz** [comment]
@mrickard created the PR #41 it would be good to know what you think it has both a new feature and example tests
