### ISSUE TITLE
Cannot find module './newrelic-lambda-wrapper.js'

### ISSUE THREAD

**Issue by MichaelHirn** [iopipe/serverless-newrelic-lambda-layers#35]
I get the above error message when invoking my lambda function.

My setup:

serverless.yml
```
# app and org for use with dashboard.serverless.com
...
plugins:
  - ...
  - serverless-newrelic-lambda-layers

provider:
  name: aws
  runtime: nodejs10.x
  ...
  region: eu-west-2
  ...
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  environment:
    NODE_ENV: ${self:provider.stage}
    DEBUG: jigsawLambda*

custom:
  config: ${file(./config/${self:provider.stage}.yml)}
  newRelic:
    accountId: ...

functions:
  test1:
    description: Test1
    handler: src/test1.handler
    reservedConcurrency: 1
    memorySize: 256
    timeout: 120
    tracing: true
```

```
sls version
---
Framework Core: 1.60.4
Plugin: 3.2.6
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0
```

**Comment by MichaelHirn** [comment]
After some investigation I found out that this error happened for me because the log subscription filter limit for lambda functions (AWS default is 1 subscription per lambda function) was exhausted.

I would see a warnings like this

```
Serverless: WARNING: Found a log subscription filter that was not installed by New Relic. This may prevent the New Relic log subscription filter from being installed. If you know you don't need this log subscription filter, you should first remove it and rerun this command. If your organization requires this log subscription filter, please contact New Relic at serverless@newrelic.com for assistance with getting the AWS log subscription filter limit increased.
```

And this somewhat cryptic message

```
Serverless: Resource limit exceeded.
```

I found there to be at least two solutions to this problem:

### Solution 1: Disable Serverless Log Subscription Filters

It turns out that serverless (at least if you are using their dashboard service) sets up their own log subscription filters, which, ones it comes to setting up the New Relic subscription filters, is then usually exhausted hence the generic `Resouce limit exceeded` error.

Good news though, you can quickly disable serverless registering its subscription filters by removing `app` and `org` keys in the root of your `serverless.yml`. This might be only a temporary solution so on to solution 2.

### Solution 2: Contact New Relic support

For a more permanent solution, especially if you want to keep using serverless' dashboard, you should get in touch with the New Relic support - just like the warning says. They will help you increase the AWS log subscription filter by handling communication with AWS. I think turn around is 1 - 2 business days if approved by AWS.

**Comment by kolanos** [comment]
@MichaelHirn Thanks for the follow up on this. Were you able to get your subscription filter limit increased?

**Comment by MichaelHirn** [comment]
Yeah, I think they did increase the limit after a couple of days for us
